title: Efe Varol Bedelcigil
name: Efe Varol Bedelcigil
description: "Elektrik-Elektronik Mühendisi Adayı"
url: "https://efebedelcigil.github.io"
baseurl: ""
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default"

author:
  name: "Efe Varol Bedelcigil"
  avatar: "/assets/images/profile.jpg"
  bio: "Ege Üniversitesi Elektrik-Elektronik Mühendisliği Öğrencisi."
  location: "İzmir, Türkiye"
  links:
    - label: "E-mail"
      icon: "fas fa-fw fa-envelope"
      url: "/tr/contact/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/efevarolbedelcigil"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/efebedelcigil"
    - label: "CV İndir (TR)"
      icon: "fas fa-fw fa-file-pdf"
      url: "/assets/pdf/cv-tr.pdf"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
  
footer:
  links:
    - label: "LinkedIn"
      url: "https://linkedin.com/in/kullaniciadi"
      icon: "fab fa-fw fa-linkedin"
    - label: "GitHub"
      url: "https://github.com/efebedelcigil"
      icon: "fab fa-fw fa-github"
    - label: "Email"
      url: "/tr/contact/"
      icon: "fas fa-fw fa-envelope"

defaults:
  - scope:
      path: "tr"
    values:
      language: "tr"
      layout: "single"
      author_profile: true
      sidebar:
        nav: "sidebar_tr"
  - scope:
      path: "en"
    values:
      language: "en"
      layout: "single"
      author_profile: true
      sidebar:
        nav: "sidebar_en"