title: Efe Varol Bedelcigil
name: Efe Varol Bedelcigil
description: "Elektrik-Elektronik Mühendisi Adayı"
url: "https://efebedelcigil.github.io"
baseurl: ""
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default"

author:
  name: "Efe Varol Bedelcigil"
  bio: "Ege Üniversitesi Elektrik-Elektronik Mühendisliği 3. Sınıf Öğrencisi."
  location: "Bornova, İzmir"

plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  - scope:
      path: "tr"
    values:
      language: "tr"
      layout: "single"
      author_profile: true
      sidebar:
        nav: "sidebar_tr"
  - scope:
      path: "en"
    values:
      language: "en"
      layout: "single"
      author_profile: true
      sidebar:
        nav: "sidebar_en"