title: Efe Varol Bedelcigil
title_seperator: " | "
name: Efe Varol Bedelcigil
description: "Elektrik-Elektronik Mühendisliği Öğrencisi"
url: "https://efebedelcigil.github.io"
baseurl: ""
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
  
footer:
  links:
    - label: "LinkedIn"
      url: "https://linkedin.com/in/efevarolbedelcigil"
      icon: "fab fa-fw fa-linkedin"
    - label: "GitHub"
      url: "https://github.com/efebedelcigil"
      icon: "fab fa-fw fa-github"
    - label: "Email"
      url: "/tr/contact/"
      icon: "fas fa-fw fa-envelope"

defaults:
  # TR Klasörü Ayarları
  - scope:
      path: "tr"
      type: "pages"
    values:
      lang: "tr"
      layout: "single"
      author_profile: true
      sidebar:
        nav: "sidebar_tr"
      language: "tr"
      author: "efe_tr"

  # EN Klasörü Ayarları
  - scope:
      path: "en"
      type: "pages"
    values:
      lang: "en"
      layout: "single"
      author_profile: true
      sidebar:
        nav: "sidebar_en"
      language: "en"
      author: "efe_en"

search: true
search_provider: lunr #to implement search button, we are not using lunr otherwise